modLoader = "javafml"
loaderVersion = "[31,)"

[[mods]]
modId = "pcg"
version = "${file.jarVersion}"
displayName = "PowerCraft Gates"
logoFile = "pcgates.png"
authors = "Razzokk"
description = '''PowerCraft Gates is a Mod that brings back the old Gates from PowerCraft'''

[[dependencies.pcg]]
modId = "forge"
mandatory = true
versionRange = "[31,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pcg]]
modId = "minecraft"
mandatory = true
versionRange = "[1.15.2]"
ordering = "NONE"
side = "BOTH"
