modLoader = "javafml"
loaderVersion = "[32,)"
license="GNU GPL v3"

[[mods]]
modId = "pcg"
version = "${file.jarVersion}"
displayName = "PowerCraft Gates"
logoFile = "pcgates.png"
authors = "Razzokk"
description = '''PowerCraft Gates is a Mod that brings back the old Gates from PowerCraft'''

[[dependencies.pcg]]
modId = "forge"
mandatory = true
versionRange = "[32,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.pcg]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16,)"
ordering = "NONE"
side = "BOTH"
